# Generated by Django 4.2 on 2023-07-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Заявки')),
                ('num_of_entries', models.IntegerField(verbose_name='Количество заявок')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=60, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('price', models.CharField(max_length=25, verbose_name='Цена')),
            ],
        ),
    ]
